#!/usr/bin/env python2.7

# Python script to control LED connected do RPi`s GPIO pin 18 by a button connected to pin 17
#
# More at http://raspberrypi.tomasgreno.cz/leds-and-buttons.html

import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

while True:

    try:

        GPIO.wait_for_edge(17, GPIO.FALLING)

        gpio_value_file = open("/sys/class/gpio/gpio18/value", "r")
        value = gpio_value_file.read();
        gpio_value_file.close()

        bool_value = int(value)

        if bool_value == 0:
            text_file = open("/sys/class/gpio/gpio18/value", "w")
            text_file.write("1")
            text_file.close()
            time.sleep(0.5)

        else:
            text_file = open("/sys/class/gpio/gpio18/value", "w")
            text_file.write("0")
            text_file.close()
            time.sleep(0.5)

    except KeyboardInterrupt:
        GPIO.cleanup()

GPIO.cleanup()
