#!/usr/bin/env python2.7

# Python script to light up or turn off LED connected to RPi`s GPIO pin 18
# At execution of this script, the actual state of LED will be inversed
#
# More at http://raspberrypi.tomasgreno.cz/leds-and-buttons.html

import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)

gpio_value_file = open("/sys/class/gpio/gpio18/value", "r")
value = gpio_value_file.read();
gpio_value_file.close()

bool_value = int(value)

if bool_value == 0:
    text_file = open("/sys/class/gpio/gpio18/value", "w")
    text_file.write("1")
    text_file.close()

else:
    text_file = open("/sys/class/gpio/gpio18/value", "w")
    text_file.write("0")
    text_file.close()

GPIO.cleanup()
