#!/usr/bin/env python2.7

# Python script to detect button press of a button connected to RPi`s GPIO pin 17
# At each button press, script will print "Button press detected!"
# Enhanced for use with microswitches, suffering from bouncing effect
#
# More at http://raspberrypi.tomasgreno.cz/leds-and-buttons.html

import subprocess
import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

while True:

    try:
        GPIO.wait_for_edge(17, GPIO.FALLING)
        subprocess.call(["echo Button press detected!"])
        time.sleep(0.5)

    except KeyboardInterrupt:
        GPIO.cleanup()

GPIO.cleanup()
