#!/usr/bin/env python2.7

# Python script to detect button press of a button connected do RPi`s GPIO pin 17
# At each button press, script will print "Button press detected!"
#
# More at http://raspberrypi.tomasgreno.cz/leds-and-buttons.html

import subprocess
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

while True:

    try:
        GPIO.wait_for_edge(17, GPIO.FALLING)
        subprocess.call(["echo Button press detected!"])

    except KeyboardInterrupt:
        GPIO.cleanup()

GPIO.cleanup()
